INSERT INTO users (name, email, password, country, city, province, admin) VALUES ('Jojo Leadbeatter', 'jleadbeatter2@bandcamp.com', 'UCHuhLhrTYy', 'Canada', 'Vancouver', 'BC', false),
('Tom Doretto', 'family@tooFast.com', 'family', 'Canada', 'Calgary', 'AB', true),
('Joe Simons', 'joe@gmail.com', 'easy', 'Canada', 'Burnaby', 'BC', false);


INSERT INTO listings (user_id, price, year, make, model, transmission, color, descriptions, sold, imageURL) VALUES
(2, '76814', 1985, 'Ford', 'Bronco', false, 'Goldenrod', 'Ac pyelonephritis NOS', true, 'https://i.imgur.com/5baqYTg.jpg'),
(2, '19', 1986, 'Buick', 'Riviera', true, 'Teal', 'Suicidal ideation', false, 'https://i.imgur.com/AJJu2DM.jpg'),
(2, '5084', 2005, 'Dodge', 'Ram 2500', true, 'Puce', 'Gu infection-deliv w p/p', true, 'https://i.imgur.com/kBMbnGG.jpg'),
(2, '640', 1998, 'Buick', 'Century', true, 'Khaki', 'Fx clavicle NOS-closed', false, 'https://i.imgur.com/yR365ma.jpg'),
(2, '69060', 2010, 'MINI', 'Cooper Clubman', false, 'Yellow', 'Path fx tibia fibula', true, 'https://i.imgur.com/iJgofU5.jpg'),
(2, '96443', 2006, 'Mitsubishi', 'Lancer Evolution', false, 'Green', 'Ocl art NOS wo infrct', false, 'https://i.imgur.com/7llq9et.jpg'),
(2, '40749', 1992, 'Lotus', 'Elan', true, 'Teal', '3rd brn w loss-chest wll', true, 'https://i.imgur.com/Hi7C0v1.jpg'),
(2, '61', 2008, 'Ford', 'Expedition', true, 'Orange', 'Wbc disease NEC', true, 'https://i.imgur.com/TVZRsfY.jpg'),
(2, '50', 1992, 'GMC', 'Yukon', false, 'Fuscia', 'Cl skul vlt fx-deep coma', true, 'https://i.imgur.com/6ofXx06.jpg'),
(2, '9', 2002, 'Lexus', 'IS', true, 'Orange', 'RR coll w oth obj-cycl', false, 'https://i.imgur.com/4xIntme.jpg'),
(2, '162', 2005, 'BMW', '525', false, 'Aquamarine', 'Traum hemothorax-open', false, 'https://i.imgur.com/rRBvYTL.jpg'),
(2, '873', 2009, 'Pontiac', 'G8', false, 'Maroon', 'TB sp crd absc-exam unkn', false, 'https://i.imgur.com/grI9Cqt.jpg'),
(2, '82071', 1996, 'Volvo', '960', true, 'Violet', 'Fail forceps NOS-antepar', true, 'https://i.imgur.com/AhWsadP.jpg'),
(2, '2', 2000, 'Chevrolet', 'S10', true, 'Puce', 'Vaccin for smallpox', false, 'https://i.imgur.com/5baqYTg.jpg'),
(2, '79', 2013, 'Toyota', 'Venza', false, 'Red', 'Mult nb/sb-before adm', true, 'https://i.imgur.com/AJJu2DM.jpg'),
(2, '6116', 2004, 'Isuzu', 'Ascender', true, 'Purple', 'One eye-severe/oth-unknw', false, 'https://i.imgur.com/kBMbnGG.jpg'),
(2, '93', 1993, 'Dodge', 'Viper', false, 'Pink', 'Syphil pulmonary valve', false, 'https://i.imgur.com/yR365ma.jpg'),
(2, '267', 1997, 'Lexus', 'SC', false, 'Fuscia', 'Volume depletion NOS', false, 'https://i.imgur.com/iJgofU5.jpg'),
(2, '04402', 2000, 'BMW', 'M5', true, 'Khaki', 'Prolonged preg-del', true, 'https://i.imgur.com/7llq9et.jpg'),
(2, '9', 1984, 'Ford', 'F250', false, 'Aquamarine', 'Twin-NOS-in hosp w cs', false, 'https://i.imgur.com/Hi7C0v1.jpg'),
(2, '59774', 1995, 'Chevrolet', 'Blazer', false, 'Fuscia', 'Pls cl leu w/o achv rmsn', true, 'https://i.imgur.com/TVZRsfY.jpg'),
(2, '34', 2012, 'Rolls-Royce', 'Phantom', false, 'Crimson', 'Oth curr cond-delivered', false, 'https://i.imgur.com/6ofXx06.jpg'),
(2, '53793', 2005, 'Chrysler', 'Town & Country', true, 'Indigo', 'TB lung fibros-histo dx', true, 'https://i.imgur.com/4xIntme.jpg'),
(2, '01437', 2002, 'Volkswagen', 'Jetta', true, 'Turquoise', 'Hiv counseling', false, 'https://i.imgur.com/rRBvYTL.jpg'),
(2, '75651', 2002, 'Acura', 'RSX', false, 'Green', 'Epilepsy-postpartum', false, 'https://i.imgur.com/grI9Cqt.jpg'),
(2, '5371', 1991, 'Pontiac', 'Firebird', true, 'Indigo', 'Supracondyl fx femur-cl', false, 'https://i.imgur.com/AhWsadP.jpg'),
(2, '81', 1993, 'Geo', 'Storm', true, 'Indigo', 'Illeg ab w ren fail-unsp', true, 'https://i.imgur.com/5baqYTg.jpg'),
(2, '24238', 2007, 'Acura', 'TL', false, 'Indigo', 'Zygomatic hyperplasia', true, 'https://i.imgur.com/AJJu2DM.jpg'),
(2, '48584', 1995, 'Audi', 'S6', true, 'Orange', 'Ulcerative blepharitis', true, 'https://i.imgur.com/kBMbnGG.jpg'),
(2, '3865', 2008, 'Hyundai', 'Azera', false, 'Yellow', 'Abscess of appendix', false, 'https://i.imgur.com/yR365ma.jpg'),
(2, '429', 2009, 'Land Rover', 'LR3', false, 'Red', 'Adv eff antibiotics NEC', true, 'https://i.imgur.com/iJgofU5.jpg'),
(2, '6', 2005, 'Suzuki', 'Reno', false, 'Indigo', 'Appendix injury-closed', true, 'https://i.imgur.com/7llq9et.jpg'),
(2, '30864', 1997, 'Dodge', 'Stratus', true, 'Fuscia', 'Lactation fail-unspec', true, 'https://i.imgur.com/Hi7C0v1.jpg'),
(2, '5698', 2009, 'Dodge', 'Viper', true, 'Goldenrod', 'Comb drug dep NEC-remiss', true, 'https://i.imgur.com/TVZRsfY.jpg'),
(2, '866', 1994, 'GMC', 'Jimmy', false, 'Teal', 'Mal hyp ht/kd I-IV w hf', false, 'https://i.imgur.com/6ofXx06.jpg'),
(2, '1429', 2006, 'Porsche', 'Cayenne', false, 'Purple', 'Obsessive-compulsive dis', true, 'https://i.imgur.com/4xIntme.jpg'),
(2, '03', 2002, 'Jaguar', 'XJ Series', false, 'Aquamarine', 'Spin bif w hydroceph NOS', false, 'https://i.imgur.com/rRBvYTL.jpg'),
(2, '410', 1985, 'Mercury', 'Marquis', false, 'Orange', 'Infective myositis', false, 'https://i.imgur.com/grI9Cqt.jpg'),
(2, '0054', 2002, 'Toyota', 'Celica', false, 'Fuscia', 'Alcohol abuse-episodic', true, 'https://i.imgur.com/AhWsadP.jpg'),
(2, '5154', 1976, 'Pontiac', 'Grand Prix', false, 'Red', 'Inj superf nerv head/nck', false, 'https://i.imgur.com/5baqYTg.jpg'),
(2, '101', 1990, 'Pontiac', 'Firebird', true, 'Fuscia', 'Locked twins-unspecified', false, 'https://i.imgur.com/AJJu2DM.jpg'),
(2, '98165', 2006, 'Chevrolet', 'Corvette', true, 'Yellow', 'Gonococcal bursitis', true, 'https://i.imgur.com/kBMbnGG.jpg'),
(2, '5181', 2012, 'Ford', 'F450', true, 'Orange', 'Cesarean delivery NOS', true, 'https://i.imgur.com/yR365ma.jpg'),
(2, '34', 1999, 'Ford', 'Windstar', false, 'Fuscia', 'Pois-benzodiazepine tran', true, 'https://i.imgur.com/iJgofU5.jpg'),
(2, '02855', 2007, 'Infiniti', 'QX', false, 'Yellow', 'Intern organ deficiency', false, 'https://i.imgur.com/7llq9et.jpg'),
(2, '92', 2012, 'Ram', '2500', false, 'Goldenrod', 'Delirium d/t other cond', false, 'https://i.imgur.com/Hi7C0v1.jpg'),
(2, '58', 1998, 'Chevrolet', 'Monte Carlo', false, 'Blue', 'Acc poison-antidepressnt', false, 'https://i.imgur.com/TVZRsfY.jpg'),
(2, '0', 2000, 'Mercury', 'Mountaineer', false, 'Teal', 'Perforation of esophagus', false, 'https://i.imgur.com/6ofXx06.jpg'),
(2, '0', 2010, 'Lexus', 'LS', false, 'Maroon', 'Prophylact immunotherapy', false, 'https://i.imgur.com/4xIntme.jpg'),
(2, '93566', 1992, 'Mazda', 'B-Series Plus', true, 'Mauv', 'Other jaw asymmetry', true, 'https://i.imgur.com/rRBvYTL.jpg'),
(2, '9', 2004, 'Lexus', 'SC', false, 'Violet', 'TB limb bones-micro dx', false, 'https://i.imgur.com/grI9Cqt.jpg'),
(2, '18180', 2006, 'Mercedes-Benz', 'E-Class', false, 'Orange', 'Pois-parasympatholytics', true, 'https://i.imgur.com/AhWsadP.jpg'),
(2, '87006', 2006, 'Chevrolet', 'TrailBlazer', true, 'Fuscia', 'Tk off/land-pers NEC', false, 'https://i.imgur.com/5baqYTg.jpg'),
(2, '3', 1995, 'Mitsubishi', '3000GT', true, 'Mauv', 'Crushing injury NOS', true, 'https://i.imgur.com/AJJu2DM.jpg'),
(2, '60', 2008, 'Lamborghini', 'Gallardo', true, 'Turquoise', 'Individ sports,athletics', false, 'https://i.imgur.com/kBMbnGG.jpg'),
(2, '797', 1997, 'Mazda', 'B-Series Plus', true, 'Blue', 'Indeterminate leprosy', false, 'https://i.imgur.com/yR365ma.jpg'),
(2, '5', 1994, 'Audi', 'V8', false, 'Maroon', 'Hepatitis A with coma', true, 'https://i.imgur.com/iJgofU5.jpg='),
(2, '93815', 2011, 'Chevrolet', 'Colorado', false, 'Yellow', 'Mult birth NOS-nonhosp', true, 'https://i.imgur.com/7llq9et.jpg'),
(2, '83', 1994, 'Mitsubishi', 'Mighty Max', false, 'Red', 'Benign neo skin trunk', true, 'https://i.imgur.com/Hi7C0v1.jpg'),
(2, '0051', 1999, 'Dodge', 'Dakota Club', true, 'Teal', 'Sec malig neo urin NEC', false, 'https://i.imgur.com/TVZRsfY.jpg'),
(2, '2', 2012, 'Ford', 'F150', true, 'Purple', 'Obs chr bronc w ac bronc', true, 'https://i.imgur.com/6ofXx06.jpg'),
(2, '51409', 2000, 'Ford', 'Explorer', false, 'Indigo', 'Ch mgr wo ara w ntr w st', false, 'https://i.imgur.com/4xIntme.jpg'),
(2, '42300', 2009, 'Aston Martin', 'Vantage', false, 'Maroon', 'Abo incompat reactn NEC', false, 'https://i.imgur.com/rRBvYTL.jpg'),
(2, '5', 2000, 'Toyota', 'Echo', true, 'Blue', 'Cooking & grilling NEC', true, 'https://i.imgur.com/grI9Cqt.jpg'),
(2, '45', 1995, 'Subaru', 'SVX', true, 'Green', 'Mult myelm w remission', true, 'https://i.imgur.com/AhWsadP.jpg');


INSERT INTO favorites (user_id, listing_id, favorited) VALUES
(2, 55, true),
(1, 5, true),
(1, 29, false),
(2, 35, false),
(1, 17, true),
(2, 10, false);


INSERT INTO messages (buyer_id, listing_id, seller_id, dateTime, messageReceived, created_at) VALUES
(1, 46, 2, '4/13/2022', true, 19),
(1, 23, 2, '4/13/2022', true, 29),
(3, 23, 2,  '4/13/2022', true, 23),
(3, 46, 2, '4/13/2022', true, 15);


INSERT INTO messageListing (sender_id, receiver_id, message_id, messageText, timeSent) VALUES
(1, 2, 1, 'Hello, is this still available?', 20),
(2, 1, 1, 'Yes, it is available!', 23),
(1, 2, 2, 'Hello!', 30),
(2, 1, 2, 'Hi! How can I help you?', 31),
(3, 2, 3, 'is this still available?', 24),
(2, 3, 3, 'yes', 26),
(3, 2, 3, 'Hi, can I do a test drive?', 16),
(2, 3, 3, 'Yes, when would you like to come in?', 18);
