

insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (1, '76814', 1985, 'Ford', 'Bronco', false, 'Goldenrod', 'Ac pyelonephritis NOS', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (2, '19', 1986, 'Buick', 'Riviera', true, 'Teal', 'Suicidal ideation', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (3, '5084', 2005, 'Dodge', 'Ram 2500', true, 'Puce', 'Gu infection-deliv w p/p', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (4, '640', 1998, 'Buick', 'Century', true, 'Khaki', 'Fx clavicle NOS-closed', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (5, '69060', 2010, 'MINI', 'Cooper Clubman', false, 'Yellow', 'Path fx tibia fibula', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (6, '96443', 2006, 'Mitsubishi', 'Lancer Evolution', false, 'Green', 'Ocl art NOS wo infrct', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (7, '40749', 1992, 'Lotus', 'Elan', true, 'Teal', '3rd brn w loss-chest wll', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (8, '61', 2008, 'Ford', 'Expedition', true, 'Orange', 'Wbc disease NEC', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (9, '50', 1992, 'GMC', 'Yukon', false, 'Fuscia', 'Cl skul vlt fx-deep coma', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (10, '9', 2002, 'Lexus', 'IS', true, 'Orange', 'RR coll w oth obj-cycl', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (11, '162', 2005, 'BMW', '525', false, 'Aquamarine', 'Traum hemothorax-open', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (12, '873', 2009, 'Pontiac', 'G8', false, 'Maroon', 'TB sp crd absc-exam unkn', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (13, '82071', 1996, 'Volvo', '960', true, 'Violet', 'Fail forceps NOS-antepar', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (14, '79', 2013, 'Toyota', 'Venza', false, 'Red', 'Mult nb/sb-before adm', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (15, '2', 2000, 'Chevrolet', 'S10', true, 'Puce', 'Vaccin for smallpox', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (16, '6116', 2004, 'Isuzu', 'Ascender', true, 'Purple', 'One eye-severe/oth-unknw', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (17, '93', 1993, 'Dodge', 'Viper', false, 'Pink', 'Syphil pulmonary valve', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (18, '267', 1997, 'Lexus', 'SC', false, 'Fuscia', 'Volume depletion NOS', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (19, '04402', 2000, 'BMW', 'M5', true, 'Khaki', 'Prolonged preg-del', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (20, '9', 1984, 'Ford', 'F250', false, 'Aquamarine', 'Twin-NOS-in hosp w cs', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (21, '59774', 1995, 'Chevrolet', 'Blazer', false, 'Fuscia', 'Pls cl leu w/o achv rmsn', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (22, '34', 2012, 'Rolls-Royce', 'Phantom', false, 'Crimson', 'Oth curr cond-delivered', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (23, '53793', 2005, 'Chrysler', 'Town & Country', true, 'Indigo', 'TB lung fibros-histo dx', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (24, '01437', 2002, 'Volkswagen', 'Jetta', true, 'Turquoise', 'Hiv counseling', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (25, '75651', 2002, 'Acura', 'RSX', false, 'Green', 'Epilepsy-postpartum', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (26, '5371', 1991, 'Pontiac', 'Firebird', true, 'Indigo', 'Supracondyl fx femur-cl', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (27, '81', 1993, 'Geo', 'Storm', true, 'Indigo', 'Illeg ab w ren fail-unsp', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (28, '24238', 2007, 'Acura', 'TL', false, 'Indigo', 'Zygomatic hyperplasia', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (29, '48584', 1995, 'Audi', 'S6', true, 'Orange', 'Ulcerative blepharitis', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (30, '3865', 2008, 'Hyundai', 'Azera', false, 'Yellow', 'Abscess of appendix', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (31, '429', 2009, 'Land Rover', 'LR3', false, 'Red', 'Adv eff antibiotics NEC', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (32, '6', 2005, 'Suzuki', 'Reno', false, 'Indigo', 'Appendix injury-closed', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (33, '30864', 1997, 'Dodge', 'Stratus', true, 'Fuscia', 'Lactation fail-unspec', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (34, '5698', 2009, 'Dodge', 'Viper', true, 'Goldenrod', 'Comb drug dep NEC-remiss', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (35, '866', 1994, 'GMC', 'Jimmy', false, 'Teal', 'Mal hyp ht/kd I-IV w hf', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (36, '1429', 2006, 'Porsche', 'Cayenne', false, 'Purple', 'Obsessive-compulsive dis', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (37, '03', 2002, 'Jaguar', 'XJ Series', false, 'Aquamarine', 'Spin bif w hydroceph NOS', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (38, '410', 1985, 'Mercury', 'Marquis', false, 'Orange', 'Infective myositis', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (39, '0054', 2002, 'Toyota', 'Celica', false, 'Fuscia', 'Alcohol abuse-episodic', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (40, '5154', 1976, 'Pontiac', 'Grand Prix', false, 'Red', 'Inj superf nerv head/nck', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (41, '101', 1990, 'Pontiac', 'Firebird', true, 'Fuscia', 'Locked twins-unspecified', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (42, '98165', 2006, 'Chevrolet', 'Corvette', true, 'Yellow', 'Gonococcal bursitis', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (43, '5181', 2012, 'Ford', 'F450', true, 'Orange', 'Cesarean delivery NOS', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (44, '34', 1999, 'Ford', 'Windstar', false, 'Fuscia', 'Pois-benzodiazepine tran', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (45, '02855', 2007, 'Infiniti', 'QX', false, 'Yellow', 'Intern organ deficiency', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (46, '92', 2012, 'Ram', '2500', false, 'Goldenrod', 'Delirium d/t other cond', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (47, '58', 1998, 'Chevrolet', 'Monte Carlo', false, 'Blue', 'Acc poison-antidepressnt', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (48, '0', 2000, 'Mercury', 'Mountaineer', false, 'Teal', 'Perforation of esophagus', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (49, '0', 2010, 'Lexus', 'LS', false, 'Maroon', 'Prophylact immunotherapy', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (50, '93566', 1992, 'Mazda', 'B-Series Plus', true, 'Mauv', 'Other jaw asymmetry', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (51, '9', 2004, 'Lexus', 'SC', false, 'Violet', 'TB limb bones-micro dx', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (52, '18180', 2006, 'Mercedes-Benz', 'E-Class', false, 'Orange', 'Pois-parasympatholytics', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (53, '87006', 2006, 'Chevrolet', 'TrailBlazer', true, 'Fuscia', 'Tk off/land-pers NEC', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (54, '3', 1995, 'Mitsubishi', '3000GT', true, 'Mauv', 'Crushing injury NOS', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (55, '60', 2008, 'Lamborghini', 'Gallardo', true, 'Turquoise', 'Individ sports,athletics', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (56, '797', 1997, 'Mazda', 'B-Series Plus', true, 'Blue', 'Indeterminate leprosy', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (57, '5', 1994, 'Audi', 'V8', false, 'Maroon', 'Hepatitis A with coma', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (58, '93815', 2011, 'Chevrolet', 'Colorado', false, 'Yellow', 'Mult birth NOS-nonhosp', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (59, '83', 1994, 'Mitsubishi', 'Mighty Max', false, 'Red', 'Benign neo skin trunk', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (60, '0051', 1999, 'Dodge', 'Dakota Club', true, 'Teal', 'Sec malig neo urin NEC', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (61, '2', 2012, 'Ford', 'F150', true, 'Purple', 'Obs chr bronc w ac bronc', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (62, '51409', 2000, 'Ford', 'Explorer', false, 'Indigo', 'Ch mgr wo ara w ntr w st', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (63, '42300', 2009, 'Aston Martin', 'Vantage', false, 'Maroon', 'Abo incompat reactn NEC', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (64, '5', 2000, 'Toyota', 'Echo', true, 'Blue', 'Cooking & grilling NEC', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (65, '45', 1995, 'Subaru', 'SVX', true, 'Green', 'Mult myelm w remission', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (66, '9008', 1993, 'Chevrolet', 'Beretta', false, 'Indigo', 'Placental polyp-unspec', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (67, '33575', 2011, 'Toyota', 'Camry', true, 'Turquoise', 'TB of ear-oth test', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (68, '8', 2008, 'Kia', 'Sorento', false, 'Violet', 'Hard tiss dis teeth NOS', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (69, '4936', 2009, 'Saturn', 'VUE', false, 'Mauv', 'Oth coll mov obj-per NOS', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (70, '2', 1999, 'GMC', 'Suburban 1500', true, 'Pink', 'Schizophrenia NOS-chr', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (71, '3445', 1992, 'Volkswagen', 'Passat', true, 'Maroon', 'Ac nonsup otitis med NOS', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (72, '1', 1991, 'Porsche', '911', false, 'Mauv', 'Onchocerciasis', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (73, '07', 1987, 'Ford', 'Laser', true, 'Aquamarine', 'Orbital periostitis', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (74, '8', 1992, 'Pontiac', 'Bonneville', false, 'Maroon', 'Neonatal hemorrhage NOS', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (75, '9', 1992, 'BMW', '5 Series', false, 'Yellow', 'Second syphilis relapse', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (76, '90', 1988, 'Mitsubishi', 'Pajero', false, 'Aquamarine', 'Dvrtcli colon w/o hmrhg', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (77, '700', 2004, 'Lamborghini', 'Murciélago', true, 'Goldenrod', 'Psychogenic disorder NOS', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (78, '10', 2009, 'Mercury', 'Grand Marquis', true, 'Indigo', 'Gonococcal eye NEC', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (79, '2188', 1993, 'Volkswagen', 'Fox', false, 'Indigo', 'Pityriasis versicolor', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (80, '5719', 1991, 'Mercedes-Benz', 'W201', true, 'Orange', 'Lymphangitis', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (81, '368', 1984, 'Pontiac', 'Firefly', true, 'Yellow', 'Athscl extrm bps gft NOS', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (82, '8655', 2009, 'Nissan', 'Murano', true, 'Teal', 'Fracture NOS-closed', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (83, '1', 2012, 'McLaren', 'MP4-12C', false, 'Violet', 'TB of spleen-unspec', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (84, '42', 2011, 'Cadillac', 'DTS', true, 'Blue', 'Adv eff quinoline', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (85, '2476', 2012, 'Hyundai', 'Veracruz', true, 'Pink', 'Prolong 1st stage-deliv', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (86, '45', 1994, 'Mitsubishi', 'Precis', false, 'Violet', 'Malig neopl pleura NOS', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (87, '6014', 2009, 'Chevrolet', 'Suburban 1500', true, 'Mauv', 'Chldhd onset flncy disor', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (88, '64510', 1987, 'Mercedes-Benz', 'SL-Class', true, 'Puce', 'Opn cort contu-deep coma', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (89, '3', 2010, 'Chevrolet', 'Avalanche', true, 'Yellow', 'War inj:con warfare NOS', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (90, '49736', 1991, 'Saab', '900', true, 'Mauv', 'Hodgkins mix cell pelvic', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (91, '10113', 2006, 'Bentley', 'Arnage', true, 'Blue', 'Hx of neurosis', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (92, '1126', 2000, 'Isuzu', 'Trooper', true, 'Blue', 'Hx estrogen therapy', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (93, '77', 2010, 'GMC', 'Canyon', true, 'Blue', 'Paratyphoid fever c', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (94, '2', 1986, 'Lotus', 'Esprit', true, 'Goldenrod', 'Ocl art NOS wo infrct', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (95, '53561', 2008, 'Audi', 'Q7', false, 'Indigo', 'Benign neoplasm eyeball', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (96, '3', 2001, 'Acura', 'NSX', false, 'Indigo', 'Senile atrophy, choroid', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (97, '44', 2010, 'Chevrolet', 'Camaro', false, 'Crimson', 'Aseptic necrosis talus', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (98, '50', 2012, 'MINI', 'Cooper', true, 'Green', 'Thrombophlebitis migrans', false);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (99, '5130', 1985, 'Mitsubishi', 'Mirage', false, 'Mauv', 'Renal cort necrosis NOS', true);
insert into listings (id, price, year, make, model, transmission, color, descritption, sold) values (100, '724', 2006, 'BMW', 'M Roadster', true, 'Yellow', 'Coag def hemorr-deliver', false);


